### ISSUE TITLE
Create Compose MySQL connector with SSL

### ISSUE THREAD

**Issue by snowch** [IBM-Bluemix/bluemix-cloud-connectors#11]
I've created a Compose MySQL connector using SSL [here](https://github.com/snowch/hello-spring-cloud/blob/master/src/main/java/helloworld/ComposeForMySqlServiceSSLInfoCreator.java).  The project will only work for Java 8 at the moment.  It also has a dependency on the following project to manage the compose certificate:

```
        <dependency>
                <groupId>com.orange.clara.cloud.boot.ssl-truststore-gen</groupId>
                <artifactId>spring-boot-ssl-truststore-gen</artifactId>
                <version>2.0.21</version>
        </dependency>
```

The ssl-truststore-gen code is Apache 2.0 Licensed so the code could be copied into this project.

**Comment by BarDweller** [comment]
Cleaning up old issues...

Sadly the older compose connectors have been retired, but their replacements in bluemix-cloud-connectors ("DatabasesFor...") do support ssl certificate handling. MySQL is unfortunately not included in the replacement connectors.
