### ISSUE TITLE
Create ComposeForPostgresqlSSLServiceInfoCreator 

### ISSUE THREAD

**Issue by snowch** [IBM-Bluemix/bluemix-cloud-connectors#12]
It would be great if we had a Postgresql Service Info Creator that supported the ssl endpoint.

See here for a mysql example: https://github.com/snowch/hello-spring-cloud/blob/master/src/main/java/helloworld/ComposeForMySqlServiceSSLInfoCreator.java

**Comment by BarDweller** [comment]
Cleaning up old issues...

Sadly the older compose connectors have been retired, but their replacements in bluemix-cloud-connectors ("DatabasesFor...") do support ssl certificate handling. This includes the Databases for PostgreSQL connector.
