### ISSUE TITLE
Does the ComposeForMongoDBCreator respects the ssl Flag

### ISSUE THREAD

**Issue by PG2000** [IBM-Bluemix/bluemix-cloud-connectors#9]
If i want to connect to a mongodb compose instance.
Is the ComposeForMongoDBCreator able to respect the sslCaFile which is provided within the vcap service env.

**Comment by BarDweller** [comment]
Cleaning up old Issues...

The ComposeForMongoDBCreator did not have any special handling for the sslCaFile, but it's replacement, the DatabasesForMongoDBCreator does understand the ssl certificate passed within it's vcap_services.
